spring:
  application:
      name: spring-boot-redis-count
  data:
    redis:
      host: 81.70.101.216
      port: 6379
      password: 123456
      database: 1
      timeout: 259200000  # ??????????2.0 ????????Duration???????????????
      # ??????2.0?????jedis??lettuce?????  jedis?? lettuce
      jedis:
        pool:
          # ???????
          max-idle: 500
          # ???????
          min-idle: 50
          # ??????????????????
          max-wait: -1
          # ??????????????
          max-active: -1
server:
  port: 8085
logging:
  level:
    io:
      lettuce:
        core: DEBUG